### PR TITLE
[Optional or for future PR] Allow to encrypt database connection in installation

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Allow to encrypt database conenction also in the moment of installation.
Read the commits titles to better understand what was done to achieve this.

### CODE REVIEW

**Comment by richard67** [comment]
Code review did not show me any unexpected ")" ... so the only idea I have is that one of the language strings which uses "(" and ")" is used at a place where it should not contain these "(" and ")" ... but why does that not fail in the CMS PR which I've made based on your code, where we use language strings with the same content?

**Comment by andrepereiradasilva** [comment]
will check

**Comment by andrepereiradasilva** [comment]
so i make some commits but just for adding hints (form input field placeholder) and revieing the language strings
I had no issue when installing .. could not replicat your issue (maybe browser cache?)

**Comment by richard67** [comment]
Well, maybe I had forgotten to pack something into the package for testing. It needs the changes in db package from framework, the changes in my PR for the CMS and the changes here, I think. Maybe I had forgotten one of these.

**Comment by richard67** [comment]
@andrepereiradasilva Sorry deleted my branch after PR to CMS was merged, have forgotten about this one.

**Comment by richard67** [comment]
@andrepereiradasilva Could you redo this PR against my new branch extra for that? [https://github.com/richard67/joomla-cms/tree/4.0-dev-tls-encrypt-db-connections-at-install](https://github.com/richard67/joomla-cms/tree/4.0-dev-tls-encrypt-db-connections-at-install)

**Comment by andrepereiradasilva** [comment]
done https://github.com/richard67/joomla-cms/pull/12

**Comment by richard67** [comment]
Thanks a lot.

**Pull request closed without merging**
