### PR TITLE
Fix conflicts

### PR DESCRIPTION
**Pull request by wilsonge**
Merge Staging into your branch

### CODE REVIEW

**Comment by richard67** [comment]
Thanks @wilsonge for the help. Question: Was it by purpose that this PR is for my staging branch and not the one of my PR? If so, how do I continue after I merged it into my staging? I am not a git guru as you might already have noticed, but am not afraid of the shell, so if there is no button to click I would survive that.

**Comment by wilsonge** [comment]
It wasn't! Sorry! Will fix when I get home later

**Comment by richard67** [comment]
Am just reading a bit "git for developers" ... maybe I will try to help myself for learning meanwhile.

Did yo hear something from Michale about the unit tests? Or if he has no time, could go give me some hints?

Michael explaind clearly what to do for someone who is familiar with the unit tests and OOP and how it's done in Joomla!, but someone like me (old fashioned c programmer) it would need a few sausages on the way so my nose can find where the butcher's shop is (like an old dog who does not see well).

**Comment by richard67** [comment]
I helped myself meanwhile with
> git fetch upstream
git merge upstream/staging
manually resolve merge conflicts and then comitted
pushed the changes

Have to add a missing newline at the end of 1 sql and then it should be fine.

But thanks for the help.

**Pull request closed without merging**
