### PR TITLE
Added hints, language clarifications, and allow more characters for paths

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Added hints and language clarifications to the global config interface.

Remember:
- one way encryption is server encryption (which the certifcates are configured on the database server), similiar to HTTPS

- two way encryption is server encryption (which the certifcates are configured on the database server) **and** client encryption (certificates configured on the client side, i.e., joomla side). So those key, certificate,ca, capath, cipher options are for configuring the client side (joomla app server side).

### CODE REVIEW

**Comment by richard67** [comment]
@andrepereiradasilva Your 2nd last commit is called "correct minor bug and put more friendly client certificates example". But I can see only changes in the language strings. What was the "minor bug"?

**Comment by richard67** [comment]
@andrepereiradasilva Other questions: These hints with texts beginning with "ex: " I can't find anywhere else in global config of J4 and also not in J3. Are they something new? If not, where else can I find such hints? I also worry if people will understand what "ex:" means. Maybe some will be so silly and add thie "ex: " also when they enter some of the paths.

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva Your 2nd last commit is called "correct minor bug and put more friendly client certificates example". But I can see only changes in the language strings. What was the "minor bug"?

minor "bug" was in the language ciphersuit string

> @andrepereiradasilva Other questions: These hints with texts beginning with "ex: " I can't find anywhere else in global config of J4 and also not in J3. Are they something new?
No they ar enot new, they exist in form fields from a long time ago. Many people don't know that.

IMHO giving this examples in input field placeholders is very good from usability perspective.

> If not, where else can I find such hints? 

Use this linux command `grep -r "hint=" --include="*.xml" /path/to/joomla/site/`

> I also worry if people will understand what "ex:" means. Maybe some will be so silly and add thie "ex: " also when they enter some of the paths.

maybe use "example: /xxxxxxx"
The problem is, if we don't put that "ex:" (or "example:") people may think that is the default value, when is just an hint to what they should do.

**Comment by richard67** [comment]
So the hints up to now are not used in global config. Other hints do not have any "ex: " or "example: " at the beginning. Examples are given at other places in the `_DESCR` texts. So I am not sure if this is good for consistenty. @wilsonge What do you think about this?

**Comment by andrepereiradasilva** [comment]
yeah, unfortunately joomla does not uses hint (input placeholder) much
But you can see some cases
- SEF Plugin canoncial domain: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/sef/sef.xml#L27
- LDAP Plugin Server Port: https://github.com/joomla/joomla-cms/blob/staging/plugins/authentication/ldap/ldap.xml#L38
- Com Config FTP Port: /var/www/html/otorrino/administrator/components/com_config/model/form/application.xml
- Com Config Proxy Port: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L447
- Com config SMTP Port: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L611
- All admin search fields
- and many others

Anyway i think it's useful, but if you guys don't, feel free to remove it. No issues at all.

**Comment by richard67** [comment]
Yes, I saw these cases, and I am very familiar with `grep` (Linux) and `findstr` (Windows).

And sure hints are useful.

But as I said, in Global Config hints are not used at all up to now, that's why I asked George for his opinion.

If he leaves it up to me, I will add them.

**Comment by richard67** [comment]
@andrepereiradasilva I will merge this and ask Brian for review in the CMS PR. I think he is the right man for checking UX consistency.

**Pull request merged**
